### ISSUE TITLE
Support Slack in social section

### ISSUE THREAD

**Issue by bittner** [edestecd/puppet-software#1]
It would be nice to have [Slack](https://slack.com/downloads/linux) available for installation from the `social` section.

<strike>If I am not mistaken then there's not even a dedicated module for installing [Slack on Puppetforge](https://forge.puppet.com/tags/slack), yet. One reason more to include it in this module.</strike> Note: There is a [dedicated Slack package](https://forge.puppet.com/jhoblitt/slack) on Puppetforge.

**Comment by edestecd** [comment]
I agree. I'm planning on switching to brew cask for mac apps soon... I can add it then

**Comment by edestecd** [comment]
Or feel free to make a PR if you have time

**Comment by bittner** [comment]
I am looking at [the source of the slack module](https://github.com/jhoblitt/puppet-slack/blob/master/manifests/init.pp) on Puppetforge, and I'm wondering why there are [so many `deps` for Ubuntu](https://github.com/jhoblitt/puppet-slack/blob/master/manifests/init.pp#L21-L32), and why the Debian package [from the Slack website](https://slack.com/downloads/linux) wouldn't install that automatically.

For the rest of the task it's really [just a few lines](https://github.com/jhoblitt/puppet-slack/blob/master/manifests/init.pp#L60-L65), as usual.

**Comment by bittner** [comment]
Would it be fine if I made a PR with just GNU/Linux (Debian/Ubuntu + Fedora) support for now? It would be a nicely short, slick solution, just an `archive` and a `package` declaration.

But no Mac and Windows for now. I have no easy way to test against those OSes.

**Comment by edestecd** [comment]
No problem on adding just Linux. I'll get the others later...
