### ISSUE TITLE
Add PDK to development (new section?)

### ISSUE THREAD

**Issue by bittner** [edestecd/puppet-software#14]
[Puppet Development Toolkit](https://github.com/puppetlabs/pdk) (PDK) is only available via [manual download](https://puppet.com/download-puppet-development-kit) and [installation](https://puppet.com/docs/pdk/1.0/pdk_install.html).

Proposed Solution
---------------
A Puppet-based installation would look like this:

```puppet
  archive { 'pdk.deb':
    source  => 'https://pm.puppetlabs.com/cgi-bin/pdk_download.cgi?dist=ubuntu&rel=16.04&arch=amd64&ver=latest',
    path    => '/tmp/pdk.deb',
    extract => false,
    cleanup => false,
  }

  package { 'pdk':
    ensure   => present,  # latest? (to make sure dpkg upgrades an installed package)
    source   => '/tmp/pdk.deb',
    provider => 'dpkg',
  }
```

Maybe Reconsider `vcsscm`
-------------------
It may be worth reconsidering the modules structure for `vcsscm` (try to understand whether moving that under a `development` category would be clearer).

**Comment by bittner** [comment]
See also https://github.com/puppetlabs/pdk/issues/324 (yum/apt/choco repos).

**Comment by bittner** [comment]
@edestecd Any comment on this?

Would this be valuable as a temporary solution as long as there are no official repositories for unattended installation? Or should we close this issue?

**Comment by edestecd** [comment]
I think we should add it if you have time.
I think it should go here: https://github.com/edestecd/puppet-software/tree/master/manifests/idesdk

Since its an sdk or dev environment

**Comment by bittner** [comment]
PDK is now available via package sources for both `yum` and `apt`. See [the PuppetLabs issue tracker](https://tickets.puppetlabs.com/browse/PDK-586) for explanations, [the setup instructions](https://puppet.com/docs/pdk/1.3/pdk_install.html#install-pdk-from-the-repository) for details.
