### ISSUE TITLE
Add tab completion and fancy prompt to Git

### ISSUE THREAD

**Issue by bittner** [edestecd/puppet-software#4]
Would you be interested to have two additional features added to the [Git class](https://github.com/edestecd/puppet-software/blob/master/manifests/vcsscm/git.pp)?

- tab completion (based on [bash-completion](https://packages.debian.org/wheezy/bash-completion), which activates [git-completion.bash](https://github.com/git/git/blob/master/contrib/completion/git-completion.bash) if I'm not mistaken)
- Git prompt (based on [bash-git-prompt](https://github.com/magicmonty/bash-git-prompt))

Using this could look like this:

``` puppet
  class { 'software::vcsscm::git':
    ensure          => present,
    bash_completion => true,
    bash_prompt     => true,
    gui             => true,
  }
```

`bash_*` because: it really just relates to Bash, and would be difficult to generically implement this for several shells (in an "autodetect shell" way).

If you think that would be a good addition, I would open a PR for that. Though, I would (have to) limit my contribution to a Debian/Ubuntu implementation. No Mac, no Windows, for now.

**Comment by edestecd** [comment]
Yes, I was actually going to add the tab completion myself for osx soon. As long as its optional, i'm not against any new feature.

**Comment by edestecd** [comment]
The example you have looks good to me
