### ISSUE TITLE
Global .git/config and .git/ignore

### ISSUE THREAD

**Issue by bittner** [edestecd/puppet-software#8]
Would it make sense to also provide the option to install system-global and user-global Git configuration, including a generic set of patterns in a global .gitignore file?

``` puppet
  class { 'software::vcsscm::git':
    ensure    => present,
    gitconfig => true,
    gitignore => true,
  }
```

This would install:

- Sensible system-global Git configuration settings (in `/etc/gitconfig`)
- A set of proposed user-global Git configuration settings (in `/etc/skel/.config/git/config`)
- A proposed user-global Git ignore configuration with files that are typically ignored (in `/etc/skel/.config/git/ignore`)

Examples
-----------

FILE: `/etc/gitconfig`
```ini
# System-global Git configuration. https://git-scm.com/docs/git-config#FILES

[alias]
	permission-reset = "!git diff -p | grep -E \"^(diff|old mode|new mode)\" | sed -e \"s/^old/NEW/;s/^new/old/;s/^NEW/new/\" | git apply"
	undo-commit = reset --soft HEAD^
```

FILE: `/etc/skel/.config/git/config`
```ini
# User-global Git configuration. See /etc/gitconfig for more settings.

[sequence]
	editor = emacs -nw
```

FILE: `/etc/skel/.config/git/ignore`
```ini
# Global Git Ignore. https://git-scm.com/docs/gitignore

# Special files and folder of various OSes
.AppleDesktop
.AppleDB
.AppleDouble
.apdisk
.com.apple.timemachine.donotpresent
Desktop.ini
.directory
*.DS_Store
.fseventsd
.fuse_hidden*
.LSOverride
Network Trash Folder
.nfs*
$RECYCLE.BIN/
.Spotlight-V100
.TemporaryItems
Temporary Items
.Trash-*
.Trashes
.VolumeIcon.icns

# Various cache files and folders
.cache
.eggs/
*.egg-info/
.eslintcache
Thumbs.db
webassets-cache

# Build files and folders
**/material-design-icons/*/ios/*.imageset/Contents.json
**/material-design-icons/sprites/
**/material-design-icons/iconfont/
**/material-design-icons/*/drawable-anydpi-v21/*.xml
**/material-design-icons/**/*.png
**/material-design-icons/*/svg/design/*.svg
__pycache__/
*.py[cod]
*$py.class

# Editor and IDE files and folders
.idea
*.stTheme.cache
*.sublime-project
*.sublime-workspace
*.tmlanguage.cache
*.tmPreferences.cache
GitHub.sublime-settings

# Environments
.env
.venv
env/
venv/
ENV/
```

References
------------

- https://git-scm.com/docs/git-config#FILES
- https://git-scm.com/docs/gitignore#_synopsis
- `git config --list --show-origin` ... shows where which config setting comes from
- `man git-config` ([FILES section](https://www.kernel.org/pub/software/scm/git/docs/git-config.html#FILES))

**Comment by bittner** [comment]
@edestecd If that's roughly okay for you I'd prepare another PR.

**Comment by edestecd** [comment]
Yea, managing git config files seams like a nice feature to add.

Could gitconfig or gitignore be a hash or path to a template. I'm not sure what defaults would be sensible for everyone. I assume many may want different settings there.

**Comment by bittner** [comment]
Difficult to say. What would you suggest in detail?

I would start just with files, and later extend the feature set to a dictionary that allows to set details of those files (technically by help of a template).

**Comment by bittner** [comment]
Yay! :tada: -- Thanks for your awesome support!
